[package]
name = "rs-bank-summary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "bank_summary"


[dependencies]
thirtyfour = "0.32.0"
chrono = "0.4.38"
async-std = "1.12.0"